fix: fix syntax pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -172,7 +172,7 @@ detect-changed-folders:
   #when: manual
 
 
-  # Stage 2: Prepare docker build
+# Stage 2: Prepare docker build
 generate-build-stage:
   stage: prepare-docker-build
   extends:
@@ -185,7 +185,7 @@ generate-build-stage:
   needs:
   - job: detect-changed-folders
     artifacts: true
-  script:
+script:
   - !reference [ .load-changed-dirs ]
   - |
     echo "Current DIRS in generate-build-stage: [$DIRS]" # Debug DIRS
@@ -197,26 +197,26 @@ generate-build-stage:
     echo "Creating docker-build-pipeline.yml..."
     for DIR in $DIRS; do
       cat <<EOF >> docker-build-pipeline.yml
-      build-${DIR}-image:
-        stage: build
-        image: ${DOCKER_IMAGE}
-        services:
-          - ${DOCKER_IMAGE}
-        tags:
-          - devops-k8s-runner
-        before_script:
-          - until docker info >/dev/null 2>&1; do sleep 1; done
-          - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
-        script:
-          - ls -ltra
-          - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
-          - echo "Building ${DIR} image"
-          - IMAGE=\${HARBOR_URL}/\${HARBOR_REPO}/\${DIR}:\${CI_COMMIT_TAG}-\${CI_COMMIT_SHORT_SHA}
-          - echo "IMAGE: \${IMAGE}"
-          - docker build -t \${IMAGE} ${DIR}
-          - echo "Pushing image to registry"
-          - docker push \${IMAGE}
-      EOF
+build-${DIR}-image:
+  stage: build
+  image: ${DOCKER_IMAGE}
+  services:
+    - ${DOCKER_IMAGE}
+  tags:
+    - devops-k8s-runner
+  before_script:
+    - until docker info >/dev/null 2>&1; do sleep 1; done
+    - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
+  script:
+    - ls -ltra
+    - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
+    - echo "Building ${DIR} image"
+    - IMAGE=\${HARBOR_URL}/\${HARBOR_REPO}/\${DIR}:\${CI_COMMIT_TAG}-\${CI_COMMIT_SHORT_SHA}
+    - echo "IMAGE: \${IMAGE}"
+    - docker build -t \${IMAGE} ${DIR}
+    - echo "Pushing image to registry"
+    - docker push \${IMAGE}
+EOF
     done
   artifacts:
     paths:
