test pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -276,16 +276,16 @@ gitleaks-secret-scan:
     REPORT_FILENAME="${GITLEAKS_FOLDER}/gitleaks_scan_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report.html"
     JSON_REPORT="${GITLEAKS_FOLDER}/gitleaks_scan_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report.json"
 
-    # Create .gitleaks.toml to restrict scan scope
-    cat <<EOF > .gitleaks.toml
-      [allowlist]
-      paths = [
-        "manifest/**",  # Exclude manifest directory
-        "!(${BEESHOES_BACKEND_DIR}/**)",  # Allow only beeshoes-backend
-        "!(${BEESHOES_FRONTEND_DIR}/**)"  # Allow only beeshoes-frontend
-      ]
-    EOF
-    LOCATION_TOML_FILE=$(pwd)/.gitleaks.toml && ls -l $LOCATION_TOML_FILE || echo "Error: .gitleaks.toml not found"
+    # # Create .gitleaks.toml to restrict scan scope
+    # cat <<EOF > .gitleaks.toml
+    #   [allowlist]
+    #   paths = [
+    #     "manifest/**",  # Exclude manifest directory
+    #     "!(${BEESHOES_BACKEND_DIR}/**)",  # Allow only beeshoes-backend
+    #     "!(${BEESHOES_FRONTEND_DIR}/**)"  # Allow only beeshoes-frontend
+    #   ]
+    # EOF
+    # LOCATION_TOML_FILE=$(pwd)/.gitleaks.toml && ls -l $LOCATION_TOML_FILE || echo "Error: .gitleaks.toml not found"
     
     for DIR in $DIRS; do
       if [[ "$DIR" != "${BEESHOES_BACKEND_DIR}" && "$DIR" != "${BEESHOES_FRONTEND_DIR}" ]]; then
@@ -299,7 +299,6 @@ gitleaks-secret-scan:
         echo "Results for $DIR" >> "$REPORT_FILENAME"
         gitleaks detect --source="$DIR" \
           --no-git \ 
-          --config-path=$LOCATION_TOML_FILE \  
           --report-format=template \
           --report-template=basic.tmpl \
           --verbose \
@@ -308,7 +307,6 @@ gitleaks-secret-scan:
           echo "Secrets detected in $DIR! Generating JSON report..."
           gitleaks detect --source="$DIR" \
             --no-git \
-            --config-path=$LOCATION_TOML_FILE \
             --report-path="${JSON_REPORT}.${DIR}" \
             --report-format=json
           cat "${JSON_REPORT}.${DIR}"
@@ -497,12 +495,12 @@ snyk-scan:
 
 trivy-image-security-scan:
   stage: scan
-  extends: .docker-job-template 
+  # extends: .docker-job-template 
+  image: ${TRIVY_IMAGE}
   variables:
     GIT_STRATEGY: none
   before_script:
-  - apk add --no-cache curl
-  - curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.62.1/trivy_0.62.1_FreeBSD-64bit.tar.gz | tar -xz -C /usr/local/bin trivy
+  - apk add --no-cache curl docker-cli
   - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
   script:
   - !reference [ .load-changed-dirs ]
