test pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -39,17 +39,23 @@ variables:
   HELM_REPO: "Three-tier-app-HelmChart"
   HELM_VALUES_PATH: "./umbrella-chart/values.yaml"
 
-  # Report path
-  GITLEAKS_FOLDER: "~/security-scan-results/secrets"
-  GITLEAKS_REPORT: "${GITLEAKS_FOLDER}/gitleaks_scan_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report"
-  TRIVY_IMG_FOLDER: "~/security-scan-results/trivy-image"
-  TRIVY_IMG_REPORT: "${TRIVY_IMG_FOLDER}/trivy_img_scan_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report"
-  TRIVYFS_FOLDER: "~/security-scan-results/trivy-fs"
-  TRIVYFS_REPORT: "${TRIVYFS_FOLDER}/trivyfs_scan_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report"
-  SNYK_FOLDER: "~/security-scan-results/snyk"
-  SNYK_REPORT: "${SNYK_FOLDER}/snyk_scan_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report"
-  SONAR_FOLDER: "~/security-scan-results/sonar"
-  SONAR_REPORT: "${SONAR_FOLDER}/sonar_scan_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report"
+  # Base paths for reports
+  SECURITY_SCAN_BASE: "~/security-scan-results"
+  REPORT_NAME: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
+
+  # Report paths
+  GITLEAKS_FOLDER: "${SECURITY_SCAN_BASE}/secrets"
+  GITLEAKS_REPORT: "${GITLEAKS_FOLDER}/gitleaks_scan_${REPORT_NAME}_report"
+  TRIVY_IMG_FOLDER: "${SECURITY_SCAN_BASE}/trivy-image"
+  TRIVY_IMG_REPORT: "${TRIVY_IMG_FOLDER}/trivy_img_scan_${REPORT_NAME}_report"
+  TRIVYFS_FOLDER: "${SECURITY_SCAN_BASE}/trivy-fs"
+  TRIVYFS_REPORT: "${TRIVYFS_FOLDER}/trivyfs_scan_${REPORT_NAME}_report"
+  SNYK_FOLDER: "${SECURITY_SCAN_BASE}/snyk"
+  SNYK_REPORT: "${SNYK_FOLDER}/snyk_scan_${REPORT_NAME}_report"
+  SONAR_FOLDER: "${SECURITY_SCAN_BASE}/sonar"
+  SONAR_REPORT: "${SONAR_FOLDER}/sonar_scan_${REPORT_NAME}_report"
+  SBOM_FOLDER: "${SECURITY_SCAN_BASE}/sbom"
+  SBOM_REPORT: "${SBOM_FOLDER}/sbom_${REPORT_NAME}_report"
 
 # Template
 .docker-job-template:
@@ -85,11 +91,6 @@ variables:
 #   # Do not run the job otherwise
 #   - when: never
 
-.rules-for-precheck-manual-gate:
-  rules:
-  - if: $PRECHECK_APPROVED == "true"
-    when: always
-  - when: manual
 
 .rules-for-sonar-be:
   rules:
@@ -173,80 +174,80 @@ detect-changed-folders:
 
 
   # Stage 2: Prepare docker build
-  # generate-build-stage:
-  #   stage: prepare-docker-build
-  #   extends:
-  #   - .docker-job-template
-  #   # - .default-develop-rules
-  #   variables:
-  #     GIT_STRATEGY: clone
-  #     GIT_CHECKOUT: "true"
-  #     GIT_CLEAN_FLAGS: -ffdx
-  #   needs:
-  #   - job: detect-changed-folders
-  #     artifacts: true
-  #   script:
-  #   - !reference [ .load-changed-dirs ]
-  #   - |
-  #     echo "Current DIRS in generate-build-stage: [$DIRS]" # Debug DIRS
-  #     if [ -z "$DIRS" ]; then
-  #       echo "No directories to build"
-  #       exit 0
-  #     fi
-  #     echo "Creating docker-build-pipeline.yml..."
-  #     for DIR in $DIRS; do
-  #       cat <<EOF >> docker-build-pipeline.yml
-  #     "build ${DIR} image":
-  #       stage: build
-  #       image: ${DOCKER_IMAGE}
-  #       services:
-  #         - ${DOCKER_IMAGE}
-  #       variables:
-  #         GIT_STRATEGY: clone 
-  #         GIT_CHECKOUT: true
-  #         GIT_CLEAN_FLAGS: -ffdx
-  #       tags:
-  #         - devops-k8s-runner
-  #       before_script:
-  #         - until docker info >/dev/null 2>&1; do sleep 1; done
-  #         - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
-  #       script:
-  #         - ls -ltra
-  #         - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
-  #         - echo "Building ${DIR} image"
-  #         - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
-  #         - echo "IMAGE \${IMAGE}"
-  #         - docker build -t \${IMAGE} ./${DIR}
-  #         - echo "Pushing image to registry"
-  #         - docker push \${IMAGE}
-  #     EOF
-  #     done
-  #   artifacts:
-  #     paths:
-  #     - docker-build-pipeline.yml
-  #     expire_in: 1 day
-  #   only:
-  #   - tags
+generate-build-stage:
+  stage: prepare-docker-build
+  extends:
+  - .docker-job-template
+  # - .default-develop-rules
+  variables:
+    GIT_STRATEGY: clone
+    GIT_CHECKOUT: "true"
+    GIT_CLEAN_FLAGS: -ffdx
+  needs:
+  - job: detect-changed-folders
+    artifacts: true
+  script:
+  - !reference [ .load-changed-dirs ]
+  - |
+    echo "Current DIRS in generate-build-stage: [$DIRS]" # Debug DIRS
+    if [ -z "$DIRS" ]; then
+      echo "No directories to build"
+      exit 0
+    fi
+    echo "Creating docker-build-pipeline.yml..."
+    for DIR in $DIRS; do
+      cat <<EOF >> docker-build-pipeline.yml
+    "build ${DIR} image":
+      stage: build
+      image: ${DOCKER_IMAGE}
+      services:
+        - ${DOCKER_IMAGE}
+      variables:
+        GIT_STRATEGY: clone 
+        GIT_CHECKOUT: true
+        GIT_CLEAN_FLAGS: -ffdx
+      tags:
+        - devops-k8s-runner
+      before_script:
+        - until docker info >/dev/null 2>&1; do sleep 1; done
+        - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
+      script:
+        - ls -ltra
+        - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
+        - echo "Building ${DIR} image"
+        - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
+        - echo "IMAGE \${IMAGE}"
+        - docker build -t \${IMAGE} ./${DIR}
+        - echo "Pushing image to registry"
+        - docker push \${IMAGE}
+    EOF
+    done
+  artifacts:
+    paths:
+    - docker-build-pipeline.yml
+    expire_in: 1 day
+  only:
+  - tags
 
-  # Stage 3: Build docker image
-  # trigger-docker-build:
-  #   stage: build-docker-image
-  #   # extends: .default-develop-rules
-  #   variables:
-  #     GIT_STRATEGY: clone
-  #     GIT_DEPTH: 0
-  #   trigger:
-  #     strategy: depend
-  #     include:
-  #     - artifact: docker-build-pipeline.yml
-  #       job: generate-build-stage
-  #   needs:
-  #   - job: generate-build-stage
-  #     artifacts: true
-  #   only:
-  #   - tags
+# Stage 3: Build docker image
+trigger-docker-build:
+  stage: build-docker-image
+  # extends: .default-develop-rules
+  variables:
+    GIT_STRATEGY: clone
+    GIT_DEPTH: 0
+  trigger:
+    strategy: depend
+    include:
+    - artifact: docker-build-pipeline.yml
+      job: generate-build-stage
+  needs:
+  - job: generate-build-stage
+    artifacts: true
+  only:
+  - tags
 
-  # Stage 4: Security scan
+# Stage 4: Security scan
 gitleaks-secret-scan:
   stage: scan
   # extends: .default-develop-rules
@@ -505,8 +506,8 @@ trivy-image-security-scan:
     fi
     mkdir -p ${TRIVY_IMG_FOLDER}
     for DIR in $DIRS; do
-      # IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
-      IMAGE="harbor.deploy.io.vn/beeshoes/beeshoes-frontend:v1"
+      IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
+      # IMAGE="harbor.deploy.io.vn/beeshoes/beeshoes-frontend:v1"
       REPORT_FILENAME="${TRIVY_IMG_FOLDER}/trivy_img_scan_${DIR}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report.html"
       trivy image --format template --template "@html.tpl" --output ${REPORT_FILENAME} $IMAGE
     done
