test pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -285,7 +285,7 @@ gitleaks-secret-scan:
         "!(${BEESHOES_FRONTEND_DIR}/**)"  # Allow only beeshoes-frontend
       ]
     EOF
-    ls -l .gitleaks.toml || echo "Error: .gitleaks.toml not found"
+    ls -l .gitleaks.toml && pwd || echo "Error: .gitleaks.toml not found"
     # Combine scan results into a single HTML file
     echo "GitLeaks Scan Report>" > "$REPORT_FILENAME"
     for DIR in $DIRS; do
@@ -296,11 +296,11 @@ gitleaks-secret-scan:
       if [ -d "$DIR" ]; then
         echo "Scanning directory: $DIR"
         echo "Directory $DIR contents:"
-        ls -l "$DIR/"
-        echo "<h2>Results for $DIR</h2>" >> "$REPORT_FILENAME"
+        ls -ltra "$DIR/"
+        echo "Results for $DIR" >> "$REPORT_FILENAME"
         gitleaks detect --source="$DIR" \
           --no-git \ 
-          --config-path=.gitleaks.toml \  
+          --config-path=~/.gitleaks.toml \  
           --report-format=template \
           --report-template=basic.tmpl \
           --verbose \
@@ -316,14 +316,11 @@ gitleaks-secret-scan:
           SCAN_EXIT_CODE=1
         else
           echo "No secrets detected in $DIR"
-          echo "<p>No secrets detected in $DIR</p>" >> "$REPORT_FILENAME"
         fi
       else
         echo "Directory $DIR does not exist, skipping"
-        echo "<p>Directory $DIR does not exist</p>" >> "$REPORT_FILENAME"
       fi
     done
-    echo "</body></html>" >> "$REPORT_FILENAME"
     if [ "$SCAN_EXIT_CODE" -ne 0 ]; then
       echo "Secrets detected in at least one directory! Check reports in ${GITLEAKS_FOLDER}"
       exit 1
@@ -501,11 +498,12 @@ snyk-scan:
 
 trivy-image-security-scan:
   stage: scan
-  # extends: .default-develop-rules
-  image: ${TRIVY_IMAGE}
+  extends: .docker-job-template 
   variables:
     GIT_STRATEGY: none
   before_script:
+  - apk add --no-cache curl
+  - curl -sSL https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.55.0_Linux-64bit.tar.gz | tar -xz -C /usr/local/bin trivy
   - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
   script:
   - !reference [ .load-changed-dirs ]
@@ -528,8 +526,6 @@ trivy-image-security-scan:
     expire_in: 1 day
     reports:
       sast: "${TRIVY_IMG_FOLDER}/*.html"
-  tags:
-  - devops-k8s-runner
   only:
   - tags
 
