test pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -193,27 +193,32 @@ generate-build-stage:
       echo "No directories to build"
       exit 0
     fi
-
-    echo "Generating child pipeline"
-    DIRS=$(cat changed_dirs.txt)
+    echo "Creating docker-build-pipeline.yml..."
     for DIR in $DIRS; do
       cat <<EOF >> docker-build-pipeline.yml
-    Build ${DIR} image:
+    build ${DIR} image:
       stage: build
-      image: docker:28-dind
-      tags: 
-        - image-related
+      image: ${DOCKER_IMAGE}
       services:
-        - docker:28-dind
+        - ${DOCKER_IMAGE}
+      variables:
+        GIT_STRATEGY: clone 
+        GIT_CHECKOUT: true
+        GIT_CLEAN_FLAGS: -ffdx
+      tags:
+        - devops-k8s-runner
+      before_script:
+        - until docker info >/dev/null 2>&1; do sleep 1; done
+        - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
       script:
-        - ls -l ./Application-Code/
+        - ls -ltra
+        - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
         - echo "Building ${DIR} image"
-        - IMAGE=\$HARBOR_URL/\$PROJECT_NAME/${DIR}:\$CI_COMMIT_SHORT_SHA
-        - docker build -t \$IMAGE ./Application-Code/${DIR}
+        - IMAGE=\${HARBOR_URL}/\${HARBOR_REPO}/\${DIR}:\${CI_COMMIT_TAG}-\${CI_COMMIT_SHORT_SHA}
+        - docker build -t \${IMAGE} \${DIR}
         - echo "Pushing image to registry"
-        - echo "\$HARBOR_PASSWD" | docker login \$HARBOR_URL -u 'robot$'\$HARBOR_USERNAME --password-stdin
-        - docker push \$IMAGE
-      EOF
+        - docker push \${IMAGE}
+    EOF
     done
   artifacts:
     paths:
