fix: fix dockerfile for fe and using correctly env

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -196,6 +196,8 @@ generate-build-stage:
     fi
     echo "Creating docker-build-pipeline.yml..."
     for DIR in $DIRS; do
+      if [ "$DIR" = "${BEESHOES_FRONTEND_DIR}" ]; then
+      echo "Processing frontend directory: $DIR"
       cat <<EOF >> docker-build-pipeline.yml
     "build ${DIR} image":
       stage: build
@@ -215,12 +217,45 @@ generate-build-stage:
         - ls -ltra
         - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
         - echo "Building ${DIR} image"
+        # create env file for frontend
+        - touch ${DIR}/.env
+        - echo "REACT_APP_API_URL=${API_URL}" >> ${DIR}/.env
+        - echo "REACT_APP_GHN_TOKEN=${GHN_TOKEN}" >> ${DIR}/.env
         - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
+        - cat ${DIR}/.env
         - echo "IMAGE \${IMAGE}"
         - docker build -t \${IMAGE} ./${DIR}
         - echo "Pushing image to registry"
         - docker push \${IMAGE}
     EOF
+      else
+          echo "Processing backend directory: $DIR"
+          cat <<EOF >> docker-build-pipeline.yml
+      "build ${DIR} image":
+        stage: build
+        image: ${DOCKER_IMAGE}
+        services:
+          - ${DOCKER_IMAGE}
+        variables:
+          GIT_STRATEGY: clone
+          GIT_CHECKOUT: true
+          GIT_CLEAN_FLAGS: -ffdx
+        tags:
+          - devops-k8s-runner
+        before_script:
+          - until docker info >/dev/null 2>&1; do sleep 1; done
+          - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u "robot$"$HARBOR_USERNAME --password-stdin
+        script:
+          - ls -ltra
+          - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
+          - echo "Building ${DIR} image"
+          - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
+          - echo "IMAGE ${IMAGE}"
+          - docker build -t \${IMAGE} ./${DIR}
+          - echo "Pushing image to registry"
+          - docker push \${IMAGE}
+      EOF
+        fi
     done
   artifacts:
     paths:
@@ -611,8 +646,8 @@ generate-sbom-files:
     mkdir -p sbom-files
     for DIR in $DIRS; do
       echo "Processing directory: $DIR"
-      # IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
-      IMAGE="harbor.deploy.io.vn/beeshoes/beeshoes-frontend:v1"
+      IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
+      #IMAGE="harbor.deploy.io.vn/beeshoes/beeshoes-frontend:v1"
       docker pull $IMAGE
       docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/sbom-files:/sbom-files $TRIVY_IMAGE image --format cyclonedx -o /sbom-files/${DIR}-sbom.json $IMAGE &
     done
