tests(pipeline): test trigger pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -173,7 +173,7 @@ detect-changed-folders:
   #when: manual
 
 
-  # Stage 2: Prepare docker build
+# Stage 2: Prepare docker build
 generate-build-stage:
   stage: prepare-docker-build
   extends:
@@ -197,8 +197,8 @@ generate-build-stage:
     echo "Creating docker-build-pipeline.yml..."
     for DIR in $DIRS; do
       if [ "$DIR" = "${BEESHOES_FRONTEND_DIR}" ]; then
-      echo "Processing frontend directory: $DIR"
-      cat <<EOF >> docker-build-pipeline.yml
+        echo "Processing frontend directory: $DIR"
+        cat <<EOF >> docker-build-pipeline.yml
     "build ${DIR} image":
       stage: build
       image: ${DOCKER_IMAGE}
@@ -227,35 +227,35 @@ generate-build-stage:
         - docker build -t \${IMAGE} ./${DIR}
         - echo "Pushing image to registry"
         - docker push \${IMAGE}
-    EOF
+  EOF
       else
-          echo "Processing backend directory: $DIR"
-          cat <<EOF >> docker-build-pipeline.yml
-      "build ${DIR} image":
-        stage: build
-        image: ${DOCKER_IMAGE}
-        services:
-          - ${DOCKER_IMAGE}
-        variables:
-          GIT_STRATEGY: clone
-          GIT_CHECKOUT: true
-          GIT_CLEAN_FLAGS: -ffdx
-        tags:
-          - devops-k8s-runner
-        before_script:
-          - until docker info >/dev/null 2>&1; do sleep 1; done
-          - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u "robot$"$HARBOR_USERNAME --password-stdin
-        script:
-          - ls -ltra
-          - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
-          - echo "Building ${DIR} image"
-          - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
-          - echo "IMAGE ${IMAGE}"
-          - docker build -t \${IMAGE} ./${DIR}
-          - echo "Pushing image to registry"
-          - docker push \${IMAGE}
-      EOF
-        fi
+        echo "Processing backend directory: $DIR"
+        cat <<EOF >> docker-build-pipeline.yml
+    "build ${DIR} image":
+      stage: build
+      image: ${DOCKER_IMAGE}
+      services:
+        - ${DOCKER_IMAGE}
+      variables:
+        GIT_STRATEGY: clone
+        GIT_CHECKOUT: true
+        GIT_CLEAN_FLAGS: -ffdx
+      tags:
+        - devops-k8s-runner
+      before_script:
+        - until docker info >/dev/null 2>&1; do sleep 1; done
+        - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u "robot$"$HARBOR_USERNAME --password-stdin
+      script:
+        - ls -ltra
+        - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
+        - echo "Building ${DIR} image"
+        - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
+        - echo "IMAGE ${IMAGE}"
+        - docker build -t \${IMAGE} ./${DIR}
+        - echo "Pushing image to registry"
+        - docker push \${IMAGE}
+  EOF
+      fi
     done
   artifacts:
     paths:
