test pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -172,81 +172,81 @@ detect-changed-folders:
   #when: manual
 
 
-# Stage 2: Prepare docker build
-# generate-build-stage:
-#   stage: prepare-docker-build
-#   extends:
-#   - .docker-job-template
-#   # - .default-develop-rules
-#   variables:
-#     GIT_STRATEGY: clone
-#     GIT_CHECKOUT: "true"
-#     GIT_CLEAN_FLAGS: -ffdx
-#   needs:
-#   - job: detect-changed-folders
-#     artifacts: true
-#   script:
-#   - !reference [ .load-changed-dirs ]
-#   - |
-#     echo "Current DIRS in generate-build-stage: [$DIRS]" # Debug DIRS
-#     if [ -z "$DIRS" ]; then
-#       echo "No directories to build"
-#       exit 0
-#     fi
-#     echo "Creating docker-build-pipeline.yml..."
-#     for DIR in $DIRS; do
-#       cat <<EOF >> docker-build-pipeline.yml
-#     "build ${DIR} image":
-#       stage: build
-#       image: ${DOCKER_IMAGE}
-#       services:
-#         - ${DOCKER_IMAGE}
-#       variables:
-#         GIT_STRATEGY: clone 
-#         GIT_CHECKOUT: true
-#         GIT_CLEAN_FLAGS: -ffdx
-#       tags:
-#         - devops-k8s-runner
-#       before_script:
-#         - until docker info >/dev/null 2>&1; do sleep 1; done
-#         - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
-#       script:
-#         - ls -ltra
-#         - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
-#         - echo "Building ${DIR} image"
-#         - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
-#         - echo "IMAGE \${IMAGE}"
-#         - docker build -t \${IMAGE} ./${DIR}
-#         - echo "Pushing image to registry"
-#         - docker push \${IMAGE}
-#     EOF
-#     done
-#   artifacts:
-#     paths:
-#     - docker-build-pipeline.yml
-#     expire_in: 1 day
-#   only:
-#   - tags
+  # Stage 2: Prepare docker build
+  # generate-build-stage:
+  #   stage: prepare-docker-build
+  #   extends:
+  #   - .docker-job-template
+  #   # - .default-develop-rules
+  #   variables:
+  #     GIT_STRATEGY: clone
+  #     GIT_CHECKOUT: "true"
+  #     GIT_CLEAN_FLAGS: -ffdx
+  #   needs:
+  #   - job: detect-changed-folders
+  #     artifacts: true
+  #   script:
+  #   - !reference [ .load-changed-dirs ]
+  #   - |
+  #     echo "Current DIRS in generate-build-stage: [$DIRS]" # Debug DIRS
+  #     if [ -z "$DIRS" ]; then
+  #       echo "No directories to build"
+  #       exit 0
+  #     fi
+  #     echo "Creating docker-build-pipeline.yml..."
+  #     for DIR in $DIRS; do
+  #       cat <<EOF >> docker-build-pipeline.yml
+  #     "build ${DIR} image":
+  #       stage: build
+  #       image: ${DOCKER_IMAGE}
+  #       services:
+  #         - ${DOCKER_IMAGE}
+  #       variables:
+  #         GIT_STRATEGY: clone 
+  #         GIT_CHECKOUT: true
+  #         GIT_CLEAN_FLAGS: -ffdx
+  #       tags:
+  #         - devops-k8s-runner
+  #       before_script:
+  #         - until docker info >/dev/null 2>&1; do sleep 1; done
+  #         - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
+  #       script:
+  #         - ls -ltra
+  #         - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
+  #         - echo "Building ${DIR} image"
+  #         - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
+  #         - echo "IMAGE \${IMAGE}"
+  #         - docker build -t \${IMAGE} ./${DIR}
+  #         - echo "Pushing image to registry"
+  #         - docker push \${IMAGE}
+  #     EOF
+  #     done
+  #   artifacts:
+  #     paths:
+  #     - docker-build-pipeline.yml
+  #     expire_in: 1 day
+  #   only:
+  #   - tags
 
-# Stage 3: Build docker image
-# trigger-docker-build:
-#   stage: build-docker-image
-#   # extends: .default-develop-rules
-#   variables:
-#     GIT_STRATEGY: clone
-#     GIT_DEPTH: 0
-#   trigger:
-#     strategy: depend
-#     include:
-#     - artifact: docker-build-pipeline.yml
-#       job: generate-build-stage
-#   needs:
-#   - job: generate-build-stage
-#     artifacts: true
-#   only:
-#   - tags
+  # Stage 3: Build docker image
+  # trigger-docker-build:
+  #   stage: build-docker-image
+  #   # extends: .default-develop-rules
+  #   variables:
+  #     GIT_STRATEGY: clone
+  #     GIT_DEPTH: 0
+  #   trigger:
+  #     strategy: depend
+  #     include:
+  #     - artifact: docker-build-pipeline.yml
+  #       job: generate-build-stage
+  #   needs:
+  #   - job: generate-build-stage
+  #     artifacts: true
+  #   only:
+  #   - tags
 
-# Stage 4: Security scan
+  # Stage 4: Security scan
 gitleaks-secret-scan:
   stage: scan
   # extends: .default-develop-rules
@@ -276,17 +276,6 @@ gitleaks-secret-scan:
     REPORT_FILENAME="${GITLEAKS_FOLDER}/gitleaks_scan_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report.html"
     JSON_REPORT="${GITLEAKS_FOLDER}/gitleaks_scan_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report.json"
 
-    # # Create .gitleaks.toml to restrict scan scope
-    # cat <<EOF > .gitleaks.toml
-    #   [allowlist]
-    #   paths = [
-    #     "manifest/**",  # Exclude manifest directory
-    #     "!(${BEESHOES_BACKEND_DIR}/**)",  # Allow only beeshoes-backend
-    #     "!(${BEESHOES_FRONTEND_DIR}/**)"  # Allow only beeshoes-frontend
-    #   ]
-    # EOF
-    # LOCATION_TOML_FILE=$(pwd)/.gitleaks.toml && ls -l $LOCATION_TOML_FILE || echo "Error: .gitleaks.toml not found"
-    
     for DIR in $DIRS; do
       if [[ "$DIR" != "${BEESHOES_BACKEND_DIR}" && "$DIR" != "${BEESHOES_FRONTEND_DIR}" ]]; then
         echo "Skipping $DIR: Only ${BEESHOES_BACKEND_DIR} and ${BEESHOES_FRONTEND_DIR} are supported"
@@ -298,7 +287,7 @@ gitleaks-secret-scan:
         ls -ltra "$DIR/"
         echo "Results for $DIR" >> "$REPORT_FILENAME"
         gitleaks detect --source="$DIR" \
-          --no-git \ 
+          --no-git \
           --report-format=template \
           --report-template=basic.tmpl \
           --verbose \
@@ -502,6 +491,7 @@ trivy-image-security-scan:
   before_script:
   - apk add --no-cache curl docker-cli
   - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
+  - curl -s -o html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
   script:
   - !reference [ .load-changed-dirs ]
   - |
@@ -515,7 +505,7 @@ trivy-image-security-scan:
       # IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
       IMAGE="harbor.deploy.io.vn/beeshoes/beeshoes-frontend:v1"
       REPORT_FILENAME="${TRIVY_IMG_FOLDER}/trivy_img_scan_${DIR}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_report.html"
-      trivy image --format template --template "@contrib/html.tpl" --output ${REPORT_FILENAME} $IMAGE
+      trivy image --format template --template "@html.tpl" --output ${REPORT_FILENAME} $IMAGE
     done
   artifacts:
     paths:
