test pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -172,79 +172,79 @@ detect-changed-folders:
   #when: manual
 
 
-  # Stage 2: Prepare docker build
-generate-build-stage:
-  stage: prepare-docker-build
-  extends:
-  - .docker-job-template
-  # - .default-develop-rules
-  variables:
-    GIT_STRATEGY: clone
-    GIT_CHECKOUT: "true"
-    GIT_CLEAN_FLAGS: -ffdx
-  needs:
-  - job: detect-changed-folders
-    artifacts: true
-  script:
-  - !reference [ .load-changed-dirs ]
-  - |
-    echo "Current DIRS in generate-build-stage: [$DIRS]" # Debug DIRS
-    if [ -z "$DIRS" ]; then
-      echo "No directories to build"
-      exit 0
-    fi
-    echo "Creating docker-build-pipeline.yml..."
-    for DIR in $DIRS; do
-      cat <<EOF >> docker-build-pipeline.yml
-    "build ${DIR} image":
-      stage: build
-      image: ${DOCKER_IMAGE}
-      services:
-        - ${DOCKER_IMAGE}
-      variables:
-        GIT_STRATEGY: clone 
-        GIT_CHECKOUT: true
-        GIT_CLEAN_FLAGS: -ffdx
-      tags:
-        - devops-k8s-runner
-      before_script:
-        - until docker info >/dev/null 2>&1; do sleep 1; done
-        - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
-      script:
-        - ls -ltra
-        - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
-        - echo "Building ${DIR} image"
-        - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
-        - echo "IMAGE \${IMAGE}"
-        - docker build -t \${IMAGE} ./${DIR}
-        - echo "Pushing image to registry"
-        - docker push ${IMAGE}
-    EOF
-    done
-  artifacts:
-    paths:
-    - docker-build-pipeline.yml
-    expire_in: 1 day
-  only:
-  - tags
+# Stage 2: Prepare docker build
+# generate-build-stage:
+#   stage: prepare-docker-build
+#   extends:
+#   - .docker-job-template
+#   # - .default-develop-rules
+#   variables:
+#     GIT_STRATEGY: clone
+#     GIT_CHECKOUT: "true"
+#     GIT_CLEAN_FLAGS: -ffdx
+#   needs:
+#   - job: detect-changed-folders
+#     artifacts: true
+#   script:
+#   - !reference [ .load-changed-dirs ]
+#   - |
+#     echo "Current DIRS in generate-build-stage: [$DIRS]" # Debug DIRS
+#     if [ -z "$DIRS" ]; then
+#       echo "No directories to build"
+#       exit 0
+#     fi
+#     echo "Creating docker-build-pipeline.yml..."
+#     for DIR in $DIRS; do
+#       cat <<EOF >> docker-build-pipeline.yml
+#     "build ${DIR} image":
+#       stage: build
+#       image: ${DOCKER_IMAGE}
+#       services:
+#         - ${DOCKER_IMAGE}
+#       variables:
+#         GIT_STRATEGY: clone 
+#         GIT_CHECKOUT: true
+#         GIT_CLEAN_FLAGS: -ffdx
+#       tags:
+#         - devops-k8s-runner
+#       before_script:
+#         - until docker info >/dev/null 2>&1; do sleep 1; done
+#         - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin
+#       script:
+#         - ls -ltra
+#         - ls -l ${DIR}/ || echo "Directory ${DIR} not found"
+#         - echo "Building ${DIR} image"
+#         - IMAGE=${HARBOR_URL}/${HARBOR_REPO}/${DIR}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
+#         - echo "IMAGE \${IMAGE}"
+#         - docker build -t \${IMAGE} ./${DIR}
+#         - echo "Pushing image to registry"
+#         - docker push ${IMAGE}
+#     EOF
+#     done
+#   artifacts:
+#     paths:
+#     - docker-build-pipeline.yml
+#     expire_in: 1 day
+#   only:
+#   - tags
 
 # Stage 3: Build docker image
-trigger-docker-build:
-  stage: build-docker-image
-  # extends: .default-develop-rules
-  variables:
-    GIT_STRATEGY: clone
-    GIT_DEPTH: 0
-  trigger:
-    strategy: depend
-    include:
-    - artifact: docker-build-pipeline.yml
-      job: generate-build-stage
-  needs:
-  - job: generate-build-stage
-    artifacts: true
-  only:
-  - tags
+# trigger-docker-build:
+#   stage: build-docker-image
+#   # extends: .default-develop-rules
+#   variables:
+#     GIT_STRATEGY: clone
+#     GIT_DEPTH: 0
+#   trigger:
+#     strategy: depend
+#     include:
+#     - artifact: docker-build-pipeline.yml
+#       job: generate-build-stage
+#   needs:
+#   - job: generate-build-stage
+#     artifacts: true
+#   only:
+#   - tags
 
 # Stage 4: Security scan
 gitleaks-secret-scan:
@@ -281,16 +281,16 @@ gitleaks-secret-scan:
       [allowlist]
       paths = [
         "manifest/**",  # Exclude manifest directory
-        "!(beeshoes-backend/**)",  # Allow only beeshoes-backend
-        "!(beeshoes-frontend/**)"  # Allow only beeshoes-frontend
+        "!(${BEESHOES_BACKEND_DIR}/**)",  # Allow only beeshoes-backend
+        "!(${BEESHOES_FRONTEND_DIR}/**)"  # Allow only beeshoes-frontend
       ]
     EOF
-
+    ls -l .gitleaks.toml || echo "Error: .gitleaks.toml not found"
     # Combine scan results into a single HTML file
-    echo "<html><body><h1>GitLeaks Scan Report</h1>" > "$REPORT_FILENAME"
+    echo "GitLeaks Scan Report>" > "$REPORT_FILENAME"
     for DIR in $DIRS; do
-      if [[ "$DIR" != "beeshoes-backend" && "$DIR" != "beeshoes-frontend" ]]; then
-        echo "Skipping $DIR: Only beeshoes-backend and beeshoes-frontend are supported"
+      if [[ "$DIR" != "${BEESHOES_BACKEND_DIR}" && "$DIR" != "${BEESHOES_FRONTEND_DIR}" ]]; then
+        echo "Skipping $DIR: Only ${BEESHOES_BACKEND_DIR} and ${BEESHOES_FRONTEND_DIR} are supported"
         continue
       fi
       if [ -d "$DIR" ]; then
